import { Route, Router, useLocation } from "@solidjs/router";
import { Layout } from "@sylphx/leaf-theme-default";
import { createEffect, For, onCleanup } from "solid-js";
import { render } from "solid-js/web";
import "@sylphx/leaf-theme-default/style.css";

// @ts-expect-error - Generated by Vite plugin
import config from "virtual:leaf/config";
// @ts-expect-error - Generated by Vite plugin
import { routes } from "virtual:leaf/routes";

interface LeafRouteConfig {
	path: string;
	component: any;
	toc: any[];
	docFooter: any;
	data?: any;
}

// Convert routes to SolidJS router format
const solidRoutes: LeafRouteConfig[] = routes.map((route: any) => ({
	path: route.path === "/" ? "/" : route.path,
	component: route.component,
	toc: route.toc || [],
	docFooter: route.docFooter,
	data: route.data,
}));

const rootElement = document.getElementById("root");

if (!rootElement) {
	throw new Error("Root element not found");
}

render(
	() => (
		<Router>
			<For each={solidRoutes}>
				{(route) => (
					<Route path={route.path}>
						{() => {
							const location = useLocation();

							// Update document title based on current route
							createEffect(() => {
								const pageTitle = route.data?.frontmatter?.title;
								const siteTitle = config?.title || "Leaf";
								document.title = pageTitle
									? `${pageTitle} | ${siteTitle}`
									: siteTitle;
							});

							// Handle scroll restoration on route change
							createEffect(() => {
								const hash = location.hash;
								if (hash) {
									requestAnimationFrame(() => {
										setTimeout(() => {
											const element = document.querySelector(hash);
											if (element) {
												element.scrollIntoView({ behavior: "smooth" });
											}
										}, 100);
									});
								} else {
									window.scrollTo(0, 0);
								}
							});

							// Handle same-page hash navigation
							createEffect(() => {
								const handleHashChange = () => {
									const hash = window.location.hash;
									if (hash) {
										requestAnimationFrame(() => {
											const element = document.querySelector(hash);
											if (element) {
												element.scrollIntoView({ behavior: "smooth" });
											}
										});
									}
								};

								window.addEventListener("hashchange", handleHashChange);
								onCleanup(() =>
									window.removeEventListener("hashchange", handleHashChange),
								);
							});

							const RouteComponent = route.component;

							return (
								<Layout
									config={config}
									currentRoute={{
										path: location.pathname,
										toc: route.toc,
										docFooter: route.docFooter,
										frontmatter: route.data?.frontmatter || {},
									}}
								>
									<RouteComponent />
								</Layout>
							);
						}}
					</Route>
				)}
			</For>
			<Route path="*">
				{() => (
					<Layout config={config} currentRoute={null}>
						<div class="prose prose-slate dark:prose-invert max-w-none">
							<h1>404 - Page Not Found</h1>
							<p>The page you're looking for doesn't exist.</p>
						</div>
					</Layout>
				)}
			</Route>
		</Router>
	),
	rootElement,
);
